### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by Snorri1986** [Snorri1986/FamilyBudget#67]
1. Create DB backup
2. Make releas of version 1.0.0

**Comment by Snorri1986** [comment]
Tablew were cleaned
```
truncate table entertainment;
truncate table groceries;
truncate table health;
truncate table housing_rent;
truncate table income;
truncate table telecom;
truncate table travel;
```

**Comment by Snorri1986** [comment]
"public" da3clq4fosdocj
Task 'PostgreSQL dump' started at Tue Dec 03 21:47:40 CET 2024
pg_dump: error: aborting because of server version mismatch

pg_dump: detail: server version: 16.3; pg_dump version: 15.2

Task 'PostgreSQL dump' finished at Tue Dec 03 21:47:40 CET 2024
2024-12-03 21:47:40.683 - IO error: Process failed (exit code = 1). See error log.
2024-12-03 21:47:40.684 - java.io.IOException: Process failed (exit code = 1). See error log.
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.validateErrorCode(AbstractNativeToolHandler.java:263)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:241)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:283)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:87)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:124)

**Comment by Snorri1986** [comment]
Released
